### ISSUE TITLE
遇到了编码问题，请求解决

### ISSUE THREAD

**Issue by Dorado607** [hankcs/TreebankPreprocessing#2]
File "ctb8.py", line 103, in <module>
    combine_fids(training, join(root_path, 'train.{}'.format(ext)), task)
  File "ctb8.py", line 49, in combine_fids
    combine_files(files, out, ctb, task, add_s=True)
  File "C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master\utility.py", line 30, in combine_files
    for s in sents:
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 306, in iterate_from
    tokens = self.read_block(self._stream)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\api.py", line 481, in _read_parsed_sent_block
    return list(filter(None, [self._parse(t) for t in self._read_block(stream)]))
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 71, in _read_block
    toks = read_regexp_block(stream, start_re=r'^\(')
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 648, in read_regexp_block
    line = stream.readline()
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1222, in readline
    new_chars = self._read(readsize)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1460, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1491, in _incr_decode
    return self.decode(bytes, 'strict')
  File "C:\Anaconda\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte

(venv) C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master>python ctb8.py --ctb C:\Users\85352\Downloads\ctb8\ctb8.0 --output C:\Users\85352\Downloads\
Importing to nltk...

Generating C:\Users\85352\Downloads\train.txt
1836 files...
0.05%Traceback (most recent call last):
  File "ctb8.py", line 103, in <module>
    combine_fids(training, join(root_path, 'train.{}'.format(ext)), task)
  File "ctb8.py", line 49, in combine_fids
    combine_files(files, out, ctb, task, add_s=True)
  File "C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master\utility.py", line 30, in combine_files
    for s in sents:
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 306, in iterate_from
    tokens = self.read_block(self._stream)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\api.py", line 481, in _read_parsed_sent_block
    return list(filter(None, [self._parse(t) for t in self._read_block(stream)]))
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 71, in _read_block
    toks = read_regexp_block(stream, start_re=r'^\(')
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 648, in read_regexp_block
    line = stream.readline()
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1222, in readline
    new_chars = self._read(readsize)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1460, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1491, in _incr_decode
    return self.decode(bytes, 'strict')
  File "C:\Anaconda\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte

(venv) C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master>python ctb8.py --ctb C:\Users\85352\Downloads\ctb8\ctb8.0 --output C:\Users\85352\Downloads\
Importing to nltk...

Generating C:\Users\85352\Downloads\train.txt
1836 files...
0.05%Traceback (most recent call last):
  File "ctb8.py", line 103, in <module>
    combine_fids(training, join(root_path, 'train.{}'.format(ext)), task)
  File "ctb8.py", line 49, in combine_fids
    combine_files(files, out, ctb, task, add_s=True)
  File "C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master\utility.py", line 30, in combine_files
    for s in sents:
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 306, in iterate_from
    tokens = self.read_block(self._stream)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\api.py", line 481, in _read_parsed_sent_block
    return list(filter(None, [self._parse(t) for t in self._read_block(stream)]))
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 71, in _read_block
    toks = read_regexp_block(stream, start_re=r'^\(')
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 648, in read_regexp_block
    line = stream.readline()
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1222, in readline
    new_chars = self._read(readsize)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1460, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1491, in _incr_decode
    return self.decode(bytes, 'strict')
  File "C:\Anaconda\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte

(venv) C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master>python ctb8.py --ctb C:\Users\85352\Downloads\ctb8\ctb8.0 --output C:\Users\85352\Downloads\
Importing to nltk...

Generating C:\Users\85352\Downloads\train.txt
1836 files...
0.05%Traceback (most recent call last):
  File "ctb8.py", line 102, in <module>
    combine_fids(training, join(root_path, 'train.{}'.format(ext)), task)
  File "ctb8.py", line 48, in combine_fids
    combine_files(files, out, ctb, task, add_s=True)
  File "C:\Users\85352\Downloads\ltp_python3_demo\TreebankPreprocessing-master\utility.py", line 30, in combine_files
    for s in sents:
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 306, in iterate_from
    tokens = self.read_block(self._stream)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\api.py", line 481, in _read_parsed_sent_block
    return list(filter(None, [self._parse(t) for t in self._read_block(stream)]))
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 71, in _read_block
    toks = read_regexp_block(stream, start_re=r'^\(')
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\corpus\reader\util.py", line 648, in read_regexp_block
    line = stream.readline()
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1222, in readline
    new_chars = self._read(readsize)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1460, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "C:\Users\85352\Downloads\ltp_python3_demo\venv\lib\site-packages\nltk\data.py", line 1491, in _incr_decode
    return self.decode(bytes, 'strict')
  File "C:\Anaconda\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte

**Comment by zhangruinan** [comment]
在linux下`file ***` 看一下你数据的encoding是什么吧. 不一定是utf-8. 我前几天刚跑过, 没问题的.

**Comment by Dorado607** [comment]
> 在linux下`file ***` 看一下你数据的encoding是什么吧. 不一定是utf-8. 我前几天刚跑过, 没问题的.

问题已经解决了，谢谢您

**Comment by Vipning** [comment]
请问有PTB的数据集么？

**Comment by HRsheng** [comment]
请问这是如何解决的

**Comment by HRsheng** [comment]
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte



> 在linux下file *** 看一下你数据的encoding是什么吧. 不一定是utf-8. 我前几天刚跑过, 没问题的.
> 
> 问题已经解决了，谢谢您

请问这是怎样解决的？

**Comment by MHaoYun** [comment]
请问是怎么解决的呢？
