### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 21: illegal multibyte sequence

### ISSUE THREAD

**Issue by zhaoxf4** [hankcs/TreebankPreprocessing#4]
win10 + python3.6 + nltk3.5，出现编码问题
错误描述：
```
D:\work\TreebankPreprocessing-master> cd d:\work\TreebankPreprocessing-master && cmd /C "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\python.exe c:\Users\ZXF\.vscode\extensions\ms-python.python-2020.8.105369\pythonFiles\lib\python\debugpy\launcher 36581 -- d:\work\TreebankPreprocessing-master\ctb8.py --ctb ctb8.0/data --output test "
Converting CTB: removing xml tags...
Traceback (most recent call last):
  File "d:\work\TreebankPreprocessing-master\ctb8.py", line 83, in <module>
    convert_ctb8_to_bracketed(args.ctb, ctb_in_nltk)
  File "d:\work\TreebankPreprocessing-master\ctb8.py", line 21, in convert_ctb8_to_bracketed
    out.write(line)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 21: illegal multibyte sequence
```

**Comment by zhaoxf4** [comment]
看很多人提了这个问题，自问自答。解决方案在Pull requests里早就有了，将ctb8.py替换为 https://github.com/hankcs/TreebankPreprocessing/pull/1/commits/1cc9b0ee0a30a9a97625b70f47eb80d4116d3b99 里的，仅仅在三处写入文件的过程中指定了encoding='utf-8'。**如果用了之前的ctb8.py，记得先删除 nltk_data/corpus/ctb8**，不然直接修改后运行还会出现以下错误：
```
D:\work\TreebankPreprocessing-master> cd d:\work\TreebankPreprocessing-master && cmd /C "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\python.exe c:\Users\ZXF\.vscode\extensions\ms-python.python-2020.8.105369\pythonFiles\lib\python\debugpy\launcher 36694 -- d:\work\TreebankPreprocessing-master\ctb8.py --ctb ctb8.0/data --output test "
Importing to nltk...

Generating test\train.txt
1836 files...
0.05%Traceback (most recent call last):
  File "d:\work\TreebankPreprocessing-master\ctb80.py", line 103, in <module>
    combine_fids(training, join(root_path, 'train.{}'.format(ext)), task)
  File "d:\work\TreebankPreprocessing-master\ctb80.py", line 49, in combine_fids
    combine_files(files, out, ctb, task, add_s=True)
  File "d:\work\TreebankPreprocessing-master\utility.py", line 30, in combine_files
    for s in sents:
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\corpus\reader\util.py", line 296, in iterate_from
    tokens = self.read_block(self._stream)
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\corpus\reader\api.py", line 476, in _read_parsed_sent_block
    return list(filter(None, [self._parse(t) for t in self._read_block(stream)]))
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 71, in _read_block
    toks = read_regexp_block(stream, start_re=r"^\(")
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\corpus\reader\util.py", line 638, in read_regexp_block
    line = stream.readline()
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\data.py", line 1101, in readline
    new_chars = self._read(readsize)
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\data.py", line 1339, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\data.py", line 1370, in _incr_decode
    return self.decode(bytes, "strict")
  File "C:\Users\ZXF\AppData\Local\Programs\Python\Python36\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 29: invalid continuation byte
```
我的路径在 C:\Users\ZXF\AppData\Roaming\nltk_data\corpora\ctb8 ，不同电脑、系统不一样。可以运行以下命令查找所有可能的路径，看看 nltk_data 具体在哪个路径下:
```
python -c "import nltk;print(nltk.data.path)"
['C:\\Users\\ZXF/nltk_data', 'C:\\Users\\ZXF\\AppData\\Local\\Programs\\Python\\Python36\\nltk_data', 'C:\\Users\\ZXF\\AppData\\Local\\Programs\\Python\\Python36\\share\\nltk_data', 'C:\\Users\\ZXF\\AppData\\Local\\Programs\\Python\\Python36\\lib\\nltk_data', 'C:\\Users\\ZXF\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']
```

**Comment by zhaoxf4** [comment]
晚上仔细读了一下作者的代码，处理成分句法分析的思路大致是
1、通过 ctb8.py 第75行的 nltk.download('ptb')下载ptb（只有文件列表），创建一个可用的nltk_data路径。如果没有这个路径，后面的操作都会报错，所以无法联网下载的机器应当手动建立nltk_data路径，见上一条回答，任选一个建立即可。
2、将原始的ctb8.0处理一下，删除xml标记（比如文档标号），放到nltk_data/corpus下。
3、用nltk处理成成分句法树，重点在 ctb8.py 的第87~89行以及 utility.py的第29行
```
    ctb = LazyCorpusLoader(
        'ctb8', BracketParseCorpusReader, r'chtb_.*\.txt',
        tagset='unknown')
```
`        sents = tb.parsed_sents(file)`
我翻了nltk3.5的api，有些区别，不过仍然是兼容的。

**Comment by hankcs** [comment]
已merge，谢谢。
